### ISSUE TITLE
No favicon available

### ISSUE THREAD

**Issue by mayuri-agrawal** [dharmikjethva30/one1#34]
I want to add a favicon to this website.

**Comment by dharmikjethva30** [comment]
Sure go for it

**Comment by mayuri-agrawal** [comment]
please give the "Hacktoberfest accepted" label so that my contribution will be count in hacktoberfest.
![Screenshot (158)](https://user-images.githubusercontent.com/82519728/198992846-fef59c55-4f2d-4d30-9c44-279cff9336dd.png)

**Comment by dharmikjethva30** [comment]
Check out, it will be in waiting period
